services:
- type: web
  name: flask-app
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  healthCheckPath: /
  envVars:
  - key: FLASK_ENV
    value: production
